# Generated by Django 4.2.7 on 2023-11-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_images_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=100, verbose_name='categoría'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='types',
            field=models.ManyToManyField(related_name='categories', to='products.type', verbose_name='tipos de producto'),
        ),
    ]
