# Generated by Django 4.2.7 on 2023-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_category_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=100, verbose_name='Marca del producto'),
            preserve_default=False,
        ),
    ]
