# Generated by Django 4.2.7 on 2023-12-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_video_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='nombre del producto'),
        ),
    ]
