# Generated by Django 4.2.7 on 2023-12-07 22:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_product_video_alter_productimage_image'),
        ('shopping_cart', '0004_rename_shoppingcartitem_carritoitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarritoItem',
            new_name='ShoppingCartItem',
        ),
    ]
