# Generated by Django 4.2.7 on 2023-12-07 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_rename_carritoitem_shoppingcartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
