# Generated by Django 4.2.7 on 2023-12-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profiles_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={},
        ),
    ]
